name: Deploy Environment

on:
  pull_request:
    types:
      - closed  # Trigger when a pull request is closed (including merged)

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Default permission for accessing the repo

jobs:
  deploy-dev:
    name: Deploy Dev Resources
    if: github.event.pull_request.merged == true && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: AZURE #must match the federated credential "based on selection"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: 'azurecloud'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform/dev
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform/dev
        run: terraform apply -auto-approve
