name: Deploy Dev Environment

on:
  push:
    branches: [ dev ]
#     - dev  # Triggers on push to the dev branch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: AZURE
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: 'azurecloud'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform/dev
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform/dev
        run: terraform apply -auto-approve
